spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      ##########################
      # 设置 数据库连接地址
      ##########################
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.84.128:3306/demodb?useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: H%Rt?)QjM^j?M8
      druid:
        #链接池
        min-idle: 5
        initial-size: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存时间
        min-evictable-idle-time-millis: 30000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
        # 打开 PSCache，并且指定每个连接上 PSCache 的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filters: stat,wall,slf4j
        # Druid WebStatFilter配置
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
        # Druid StatViewServlet配置
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          reset-enable: true
          login-username: admin
          login-password: admin
        # 配置日志输出
        filter:
          slf4j:
            enabled: true
            statement-create-after-log-enabled: false
            statement-close-after-log-enabled: false
            result-set-open-after-log-enabled: false
            result-set-close-after-log-enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0