spring:
  redis:
    redisson:
      config:
        singleServerConfig:
#          password: 123456
          address: "redis://192.168.84.128:6379"
          database: 1
        threads: 0
        nettyThreads: 0
        codec: org.redisson.codec.FstCodec
        transportMode: "NIO"
    host: 192.168.84.128